### PR TITLE
Change InitError and EventError, close #28

### LINKED ISSUE #28: The example fails to compile.
The whole error is:
```
examples/hello-world.rs:29:38: 29:51 error: type `core::option::Option<rustbox::EventErrorKind::Error>` does not implement any method in scope named `description`
examples/hello-world.rs:29             Err(e) => panic!("{}", e.description()),
                                                                ^~~~~~~~~~~~~
note: in expansion of format_args!
<std macros>:9:1: 9:40 note: expansion site
<std macros>:1:1: 11:23 note: in expansion of panic!
examples/hello-world.rs:29:23: 29:52 note: expansion site
error: aborting due to previous error
Could not compile `rustbox`.
```
which can be temporarily fixed by:
```
diff --git a/examples/hello-world.rs b/examples/hello-world.rs
index d4b65e6..52a52ce 100644
--- a/examples/hello-world.rs
+++ b/examples/hello-world.rs
@@ -1,8 +1,5 @@
-#![feature(core)]
-
 extern crate rustbox;
 
-use std::error::Error;
 use std::default::Default;
 
 use rustbox::{Color, RustBox};
@@ -26,7 +23,7 @@ fn main() {
                     _ => { }
                 }
             },
-            Err(e) => panic!("{}", e.description()),
+            Err(e) => panic!("{:?}", e),
             _ => { }
         }
     }
```
using the `Debug` trait for `Option<T>`.

The `rustc` version is: rustc 1.1.0-nightly (c4b23aec4 2015-04-29) (built 2015-04-28)

I have looked into the source, and I have a (or two) question about `InitError` and `InitErrorKind`.
Is there rationale behind splitting those two? What is the purpose of `#[repr(C, isize)]`?

I am fairly new to Rust, but AFAIK `#[repr(C)]` is only needed if you need interoperability (which is not necessary in this case because Rustbox is currently a wrapper for Termbox).

Can't you just do like this:
```
#[derive(Debug)]
pub enum InitError {
    BufferStderrFailed(io::Error),
    AlreadyOpen,
    UnsupportedTerminal,
    FailedToOpenTTy,
    PipeTrapError,
    Other(isize),
}

impl fmt::Display for InitError { ... }

impl Error for InitError { ... }

impl FromPrimitive for InitError {
    // you can use `unwrap()` directly because it only returns Some(..)
    fn from_i64(n: i64) -> Option<InitError> {
        match n {
            -1 => Some(InitError::UnsupportedTerminal),
            -2 => Some(InitError::FailedToOpenTTy),
            -3 => Some(InitError::PipeTrapError),
            n => Some(Other(n as isize)),
        }
    }

    // can't convert from unsigned
    fn from_u64(n: u64) -> Option<InitError> {
        None
    }
}
```
You'd lose the benefit from using the `enum_primitive` macro, but you can tell the user what unknown error code the termbox gave.

Also, same applies to the `EventError` and `EventErrorKind`, which is quite conspicuous with "FIXME" label.

### PR DESCRIPTION
**Pull request by sru**

### CODE REVIEW

File: src/rustbox.rs [hunk 1]
```diff
@@ -89,22 +88,43 @@ mod style {
...
-// pub enum EventErrorKind {
-//     Error = -1,
-// }
-// pub type EventError = Option<EventErrorKind>;
-#[allow(non_snake_case)]
-pub mod EventErrorKind {
-    #[derive(Clone, Copy,Debug)]
-    pub struct Error;
+#[derive(Debug)]
+pub enum EventError {
```
Comment (sru) [inline src/rustbox.rs]: I don't know if this is even needed because there is no "type" of error for Termbox. It just says it returns -1 if there was an error. Could just wrap `isize` type:
```rust
pub struct EventError(isize);
```
